// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlc0oB0SN3P2C6scIFxw_ysfT6sBFissc',
    appId: '1:301982492403:web:2a306622121b272bf8f986',
    messagingSenderId: '301982492403',
    projectId: 'belajar-firebase-37845',
    authDomain: 'belajar-firebase-37845.firebaseapp.com',
    storageBucket: 'belajar-firebase-37845.appspot.com',
    measurementId: 'G-6X2PBDD0JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDRqDAGlinojZzwT9dNp2CgEoZe6vVmn6I',
      appId: '1:301982492403:android:b1274cd17ea6dd4af8f986',
      messagingSenderId: '301982492403',
      projectId: 'belajar-firebase-37845',
      storageBucket: 'belajar-firebase-37845.appspot.com',
      databaseURL:
          'https://belajar-firebase-37845-default-rtdb.firebaseio.com/');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlq4gT1dME5z8dRDpwL7G8vCxh1TWBf3o',
    appId: '1:301982492403:ios:71bf2f4de4b0c8aaf8f986',
    messagingSenderId: '301982492403',
    projectId: 'belajar-firebase-37845',
    storageBucket: 'belajar-firebase-37845.appspot.com',
    iosBundleId: 'com.example.belajarfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlq4gT1dME5z8dRDpwL7G8vCxh1TWBf3o',
    appId: '1:301982492403:ios:71bf2f4de4b0c8aaf8f986',
    messagingSenderId: '301982492403',
    projectId: 'belajar-firebase-37845',
    storageBucket: 'belajar-firebase-37845.appspot.com',
    iosBundleId: 'com.example.belajarfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlc0oB0SN3P2C6scIFxw_ysfT6sBFissc',
    appId: '1:301982492403:web:b7a496fb79ad6860f8f986',
    messagingSenderId: '301982492403',
    projectId: 'belajar-firebase-37845',
    authDomain: 'belajar-firebase-37845.firebaseapp.com',
    storageBucket: 'belajar-firebase-37845.appspot.com',
    measurementId: 'G-8VHGE9T8LW',
  );
}
